# Generated by Django 5.2.1 on 2025-05-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_directionmod_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmod',
            name='day_type',
            field=models.CharField(blank=True, max_length=30, verbose_name='Dars kunlari'),
        ),
    ]
