# Generated by Django 5.2.1 on 2025-05-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_usersmod_day_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswersmod',
            name='comment',
            field=models.TextField(blank=True, verbose_name="O'quvchi taklifi"),
        ),
    ]
