# Generated by Django 5.2.1 on 2025-05-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_useranswersmod_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmod',
            name='group_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Guruh nomi'),
        ),
    ]
