# Generated by Django 5.2.1 on 2025-05-26 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_useranswersmod_direction_useranswersmod_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswersmod',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='useranswersmod',
            name='teacher',
        ),
    ]
