# Generated by Django 5.2.1 on 2025-05-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_useranswersmod_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directionmod',
            name='name',
            field=models.CharField(max_length=100, verbose_name="Yo'nalishlar"),
        ),
    ]
