# Generated by Django 5.2.1 on 2025-05-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_directionmod_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmod',
            name='quiz_sent_today',
            field=models.BooleanField(default=False),
        ),
    ]
